- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - openstackclient-plugin-jobs
    check:
      jobs:
        - telemetry-tox-py37
    gate:
      jobs:
        - telemetry-tox-py37

